# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sanjayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='applicationname',
            field=models.CharField(default=datetime.datetime(2016, 11, 26, 10, 18, 24, 660872, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
