# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-30 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sanjayapp', '0003_auto_20170112_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='Suport_Group',
            field=models.CharField(default=datetime.datetime(2017, 1, 30, 22, 23, 19, 992744, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='Architecture',
            field=models.CharField(default=datetime.datetime(2017, 1, 30, 22, 23, 28, 321156, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='OS',
            field=models.CharField(default=datetime.datetime(2017, 1, 30, 22, 23, 43, 900640, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
